=== JnRMnT/jmovies/JMovies.App/ConfigurationFiles/Schemas/FlowConfiguration-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for flow configurations",

  "type": "object",

  "properties": {
    "Name": {
      "type": "string",
      "description": "Represents the name of the flow."
    },
    "ActionClassIdentifier": {
      "type": "string",
      "description": "Action class fully qualified identifier."
    },
    "RequestIdentifier": {
      "type": "string",
      "description": "Request Type fully qualified identifier."
    },
    "ResponseIdentifier": {
      "type": "string",
      "description": "Response Type fully qualified identifier."
    },
    "Validations": {
      "type": "array",
      "description": "Array of validations",
      "items": {
        "$ref": "#/definitions/validation"
      }

    }
  },
  "definitions": {
    "validation": {
      "type": "object",
      "description": "Validation",
      "required": [ "requestProperties", "errorResource", "serverValidator" ],
      "properties": {
        "errorResource": {
          "type": "string"
        },
        "serverValidator": {
          "type": "string",
          "enum": [
            "JMovies.Utilities.Validations.RequiredValidator, JMovies.Utilities",
            "JMovies.Utilities.Validations.PasswordRulesValidator, JMovies.Utilities",
            "JMovies.Utilities.Validations.EqualsValidator, JMovies.Utilities",
            "JMovies.Utilities.Validations.UsernameRulesValidator, JMovies.Utilities",
            "JMovies.App.Business.Validations.UsernameRulesValidator, JMovies.App.Business",
            "JMovies.App.Business.Validations.EmailExistsValidator, JMovies.App.Business",
            "JMovies.Utilities.Validations.RegexValidator, JMovies.Utilities"
          ]
        },
        "requestProperties": {
          "type": "array",
          "description": "Array of request properties",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/BasicResolutionTest.json
{
  "$schema": "../../JMovies.App/ConfigurationFiles/schemas/flowconfiguration-schema.json#",
  "Name": "BasicResolutionTest",
  "RequestIdentifier": "JMovies.Entities.Requests.BasicResolutionTestRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.BasicResolutionTestResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.BasicResolutionTest, JMovies.App.Business"
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/GetImageContents.json
{
  "$schema": "../schemas/flowconfiguration-schema.json#",
  "Name": "GetImageContents",
  "RequestIdentifier": "JMovies.Entities.Requests.GetImageContentsRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.GetImageContentsResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.GetImageContents, JMovies.App.Business"
}
