=== JnRMnT/jmovies/JMovies.App/ConfigurationFiles/Schemas/FlowConfiguration-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for flow configurations",

  "type": "object",

  "properties": {
    "Name": {
      "type": "string",
      "description": "Represents the name of the flow."
    },
    "ActionClassIdentifier": {
      "type": "string",
      "description": "Action class fully qualified identifier."
    },
    "RequestIdentifier": {
      "type": "string",
      "description": "Request Type fully qualified identifier."
    },
    "ResponseIdentifier": {
      "type": "string",
      "description": "Response Type fully qualified identifier."
    },
    "Validations": {
      "type": "array",
      "description": "Array of validations",
      "items": {
        "$ref": "#/definitions/validation"
      }

    }
  },
  "definitions": {
    "validation": {
      "type": "object",
      "description": "Validation",
      "required": [ "requestProperties", "errorResource", "serverValidator" ],
      "properties": {
        "errorResource": {
          "type": "string"
        },
        "serverValidator": {
          "type": "string",
          "enum": [
            "JMovies.Utilities.Validations.RequiredValidator, JMovies.Utilities",
            "JMovies.Utilities.Validations.PasswordRulesValidator, JMovies.Utilities",
            "JMovies.Utilities.Validations.EqualsValidator, JMovies.Utilities",
            "JMovies.Utilities.Validations.UsernameRulesValidator, JMovies.Utilities",
            "JMovies.App.Business.Validations.UsernameRulesValidator, JMovies.App.Business",
            "JMovies.App.Business.Validations.EmailExistsValidator, JMovies.App.Business",
            "JMovies.Utilities.Validations.RegexValidator, JMovies.Utilities"
          ]
        },
        "requestProperties": {
          "type": "array",
          "description": "Array of request properties",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/StaticDataManagement.json
{
  "$schema": "../../JMovies.App/ConfigurationFiles/schemas/flowconfiguration-schema.json#",
  "Name": "StaticDataManagement",
  "RequestIdentifier": "JMovies.Entities.Requests.StaticDataManagementRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.StaticDataManagementResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.StaticDataManagement, JMovies.App.Business"
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/Login.json
{
  "$schema": "../../JMovies.App/ConfigurationFiles/schemas/flowconfiguration-schema.json#",
  "Name": "Login",
  "RequestIdentifier": "JMovies.Entities.Requests.LoginRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.LoginResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.Login, JMovies.App.Business"
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/GetPersonDetails.json
{
  "$schema": "../../JMovies.App/ConfigurationFiles/schemas/flowconfiguration-schema.json#",
  "Name": "GetPersonDetails",
  "RequestIdentifier": "JMovies.Entities.Requests.GetPersonDetailsRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.GetPersonDetailsResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.GetPersonDetails, JMovies.App.Business"
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/Search.json
{
  "$schema": "../../JMovies.App/ConfigurationFiles/schemas/flowconfiguration-schema.json#",
  "Name": "Search",
  "RequestIdentifier": "JMovies.Entities.Requests.SearchRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.SearchResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.Search, JMovies.App.Business"
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/GetProductionCast.json
{
  "$schema": "../schemas/flowconfiguration-schema.json#",
  "Name": "GetProductionCast",
  "RequestIdentifier": "JMovies.Entities.Requests.GetProductionCastRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.GetProductionCastResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.GetProductionCast, JMovies.App.Business"
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/GetProductionDetails.json
{
  "$schema": "../schemas/flowconfiguration-schema.json#",
  "Name": "GetProductionDetails",
  "RequestIdentifier": "JMovies.Entities.Requests.GetProductionDetailsRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.GetProductionDetailsResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.GetProductionDetails, JMovies.App.Business"
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/Register.json
{
  "$schema": "../schemas/flowconfiguration-schema.json#",
  "Name": "Register",
  "RequestIdentifier": "JMovies.Entities.Requests.RegisterRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.RegisterResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.Register, JMovies.App.Business",
  "Validations": [
    {
      "serverValidator": "JMovies.Utilities.Validations.RequiredValidator, JMovies.Utilities",
      "errorResource": "Title.InvalidUsername",
      "requestProperties": [ "Username" ]
    },
    {
      "serverValidator": "JMovies.Utilities.Validations.RequiredValidator, JMovies.Utilities",
      "errorResource": "Title.InvalidPassword",
      "requestProperties": [ "Password" ]
    },
    {
      "serverValidator": "JMovies.Utilities.Validations.RequiredValidator, JMovies.Utilities",
      "errorResource": "Title.InvalidEmail",
      "requestProperties": [ "Email" ]
    },
    {
      "serverValidator": "JMovies.App.Business.Validations.EmailExistsValidator, JMovies.App.Business",
      "errorResource": "Title.InvalidEmail",
      "requestProperties": [ "Email" ]
    },
    {
      "serverValidator": "JMovies.Utilities.Validations.RegexValidator, JMovies.Utilities",
      "errorResource": "Title.InvalidEmail",
      "requestProperties": [ "Email", "$$^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$" ]
    },
    {
      "serverValidator": "JMovies.Utilities.Validations.EqualsValidator, JMovies.Utilities",
      "errorResource": "Title.PasswordsDontMatch",
      "requestProperties": [ "Password", "PasswordConfirm" ]
    },
    {
      "serverValidator": "JMovies.App.Business.Validations.UsernameRulesValidator, JMovies.App.Business",
      "errorResource": "Title.InvalidUsername",
      "requestProperties": [ "Username" ]
    }
  ]
}

=== JnRMnT/jmovies/JMovies.Web.UI/ConfigurationFiles/Flows/GetLastAddedProductions.json
{
  "$schema": "../../JMovies.App/ConfigurationFiles/schemas/flowconfiguration-schema.json#",
  "Name": "GetLastAddedProductions",
  "RequestIdentifier": "JMovies.Entities.Requests.GetLastAddedProductionsRequest, JMovies.Entities",
  "ResponseIdentifier": "JMovies.Entities.Responses.GetLastAddedProductionsResponse, JMovies.Entities",
  "ActionClassIdentifier": "JMovies.App.Business.Actions.GetLastAddedProductions, JMovies.App.Business"
}
